server:
  port: 80


spring:
  application:
    name: cloud-service-order

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka/